set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
function(require_contains path needle)
  file(READ "${ROOT}/${path}" TEXT)
  string(FIND "${TEXT}" "${needle}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Batch35: ${path} missing: ${needle}")
  endif()
endfunction()
require_contains("ui/DetachablePanelManager.cpp" "static_cast<QCloseEvent*>(event)->ignore()")
require_contains("ui/DetachablePanelManager.cpp" "QTimer::singleShot(0,this,[this]")
require_contains("tests/test_mainwindowui.cpp" "closingFloatingPanelReattachesAndStaysVisible")
require_contains("tests/CMakeLists.txt" "test_batch35_floating_close_reattach_contract")
message(STATUS "Batch35 floating close reattach contract passed")
