cmake_minimum_required(VERSION 3.16)
set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
function(read_file rel out)
  file(READ "${ROOT}/${rel}" _content)
  set(${out} "${_content}" PARENT_SCOPE)
endfunction()
function(require_contains text needle label)
  string(FIND "${text}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "Batch31 missing ${label}: ${needle}")
  endif()
endfunction()

read_file("tests/CMakeLists.txt" tests_cmake)
require_contains("${tests_cmake}" "../ui/DetachableTabWidget.cpp" "detachable-tab source in MainWindow UI test")
require_contains("${tests_cmake}" "../ui/CaptureSessionWidget.cpp" "capture-session source in MainWindow UI test")

read_file("protocol/Iec104SessionAnalyzer.cpp" iec)
require_contains("${iec}" "observedIFrames" "observed IEC104 I-frame bound")
require_contains("${iec}" "qMin(quint64(rawOutstanding),state.observedIFrames)" "bounded outstanding IEC104 estimate")

read_file("CMakeLists.txt" root_cmake)
foreach(src "diagnostic/AtStatusParser.cpp" "diagnostic/DualCaptureCorrelator.cpp" "protocol/Iec104SessionAnalyzer.cpp" "capture/TcpdumpTextStreamParser.cpp")
  require_contains("${root_cmake}" "${src}" "new source ${src}")
endforeach()
message(STATUS "Batch31 build integration contract passed")
