cmake_minimum_required(VERSION 3.16)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
function(read_file rel out)
  file(READ "${ROOT}/${rel}" content)
  set(${out} "${content}" PARENT_SCOPE)
endfunction()
function(req hay needle msg)
  string(FIND "${hay}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "Batch51 contract failed: ${msg}: missing [${needle}]")
  endif()
endfunction()
function(forbid hay needle msg)
  string(FIND "${hay}" "${needle}" pos)
  if(NOT pos EQUAL -1)
    message(FATAL_ERROR "Batch51 contract failed: ${msg}: found forbidden [${needle}]")
  endif()
endfunction()
read_file("MainWindow.cpp" MW)
read_file("ui/CaptureSessionWidget.cpp" CS)
read_file("telnet/TelnetClient.h" TH)
read_file("telnet/TelnetClient.cpp" TC)
read_file("capture/PacketCaptureController.cpp" PC)
read_file("diagnostic/DeviceDiscoveryController.cpp" DD)

req("${MW}" "if(info.up" "main capture interface choices must keep only UP interfaces")
req("${MW}" "ifconfig 2>/dev/null" "main refresh must use ordinary ifconfig")
forbid("${MW}" "ifconfig -a 2>/dev/null || ifconfig 2>/dev/null" "main refresh must not enumerate down interfaces")
req("${CS}" "if(info.up" "capture-session interface choices must keep only UP interfaces")
req("${CS}" "ifconfig 2>/dev/null" "capture-session refresh must use ordinary ifconfig")
forbid("${CS}" "ifconfig -a 2>/dev/null || ifconfig 2>/dev/null" "capture-session refresh must not enumerate down interfaces")

req("${TH}" "executeStreamingCommand" "TelnetClient keeps marker-free streaming support for compatible long-running commands")
req("${TC}" "void TelnetClient::executeStreamingCommand" "TelnetClient keeps marker-free streaming support")
req("${TC}" "m_serial.flush()" "serial Ctrl-C recovery nudge must be flushed promptly to the router console")
req("${PC}" "buildBackgroundTextTcpdumpCommand" "serial capture must keep the shared shell available using background tcpdump")
req("${PC}" "__WANDIAG_TCPDUMP_PID__" "serial capture must retain exact tcpdump PID for stop/recovery")

req("${DD}" "nvram get bkup_wan_ifname" "WAN discovery must query backup WAN interface")
req("${DD}" "nvram get wan_ifname2" "WAN discovery must query secondary WAN interface")
req("${DD}" "nvram get comm_wan_ipaddr" "WAN discovery must query cellular WAN IP")
req("${DD}" "nvram get current_module_name" "module discovery must query current module name")
req("${DD}" "nvram get submodulename" "module discovery must query submodule name")
req("${DD}" "nvram get comm_name" "module discovery must query communication module name")
message(STATUS "Batch51 WAN/up-interface/serial-capture contract passed")
