cmake_minimum_required(VERSION 3.16)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
function(read_file rel out)
  file(READ "${ROOT}/${rel}" content)
  set(${out} "${content}" PARENT_SCOPE)
endfunction()
function(req hay needle msg)
  string(FIND "${hay}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "Batch53 contract failed: ${msg}: missing [${needle}]")
  endif()
endfunction()
function(forbid hay needle msg)
  string(FIND "${hay}" "${needle}" pos)
  if(NOT pos EQUAL -1)
    message(FATAL_ERROR "Batch53 contract failed: ${msg}: found forbidden [${needle}]")
  endif()
endfunction()
read_file("diagnostic/DeviceDiscoveryController.cpp" DD)
read_file("capture/PacketCaptureController.cpp" PC)
read_file("MainWindow.cpp" MW)
read_file("tests/test_devicediscovery.cpp" TD)
read_file("tests/test_packetcapturecontroller.cpp" TP)

req("${TD}" "ignoresAtTestDecorationsAndParsesNeowayN511Ati" "N511 at_test output must have a regression test")
req("${DD}" "^[[:space:]]*OK[[:space:]]*$" "at_test OK detection must tolerate whitespace")
req("${DD}" "parseAtiManufacturer" "ATI should seed manufacturer")
req("${DD}" "parseAtiFirmware" "ATI should seed firmware")
req("${DD}" "-->" "at_test decoration filtering must be explicit")
req("${DD}" "nvram get controldevice" "module probe should use NVRAM device hints")
req("${DD}" "nvram get 3gdata" "module probe should use NVRAM data-device hints")

req("${TP}" "serialTextCaptureRunsTcpdumpInBackgroundAndReturnsPid" "serial capture background PID behavior must be tested")
req("${PC}" "__WANDIAG_TCPDUMP_PID__" "serial capture must capture the background tcpdump PID")
req("${PC}" "__FF_SERIAL_READY__" "serial stop must verify shell recovery")
req("${PC}" "kill -2" "serial stop must use SIGINT against the captured tcpdump PID")
forbid("${PC}" "executeStreamingCommand(m_textCaptureCommand" "serial capture must not monopolize the shared shell with a foreground streaming command")

req("${TD}" "downOnlyConfiguredWanDoesNotUseNvramIpAsLiveWan" "down configured WAN regression must exist")
req("${DD}" "requireUp" "WAN choice must evaluate link state")

req("${MW}" "RSRP %1 dBm" "signal card must display RSRP")
req("${MW}" "SINR %1 dB" "signal card must display SINR")
forbid("${MW}" "signalParts<<QStringLiteral(\"RSRQ %1 dB\")" "signal card must not display RSRQ")
forbid("${MW}" "signalParts<<QStringLiteral(\"CSQ %1\")" "signal card must not fall back to CSQ")
message(STATUS "Batch53 N511/serial/WAN/signal contract passed")
