cmake_minimum_required(VERSION 3.16)
set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
file(READ "${ROOT}/tests/test_mainwindowui.cpp" T)
file(READ "${ROOT}/ui/DetachablePanelManager.cpp" D)
function(req text needle message)
  string(FIND "${text}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "Batch47 contract failed: ${message} (missing: ${needle})")
  endif()
endfunction()
function(forbid text needle message)
  string(FIND "${text}" "${needle}" pos)
  if(NOT pos EQUAL -1)
    message(FATAL_ERROR "Batch47 contract failed: ${message} (found forbidden: ${needle})")
  endif()
endfunction()
forbid("${T}" "findChild<QLineEdit*>(\"editIface\")" "UI test must not look for removed editIface")
req("${T}" "findChild<QComboBox*>(\"comboCaptureInterface\")" "UI test must use editable capture interface combo")
req("${T}" "QCOMPARE(mode->count(),4)" "capture mode test must expect WAN/master/terminal/custom modes")
req("${T}" "QVERIFY(iface->isEditable())" "capture interface test must assert manual entry remains available")
forbid("${D}" "new QFrame(m_originalParent)" "splitter replacement wrapper must not start life as a sibling of the panel")
req("${D}" "m_wrapper=new QFrame(nullptr)" "detachable wrapper must be parentless before QSplitter::replaceWidget")
message(STATUS "Batch47 UI test + splitter warning contract passed")
