cmake_minimum_required(VERSION 3.16)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
file(READ "${ROOT}/MainWindow.cpp" MW)
file(READ "${ROOT}/tests/test_mainwindowui.cpp" T)
string(FIND "${MW}" "comboWorkspacePreset" POS)
if(NOT POS EQUAL -1)
  message(FATAL_ERROR "Batch48 supersedes the workspace selector: comboWorkspacePreset must be absent")
endif()
string(FIND "${T}" "workspaceSelectorIsRemoved" POS)
if(POS EQUAL -1)
  message(FATAL_ERROR "UI test must protect workspace selector removal")
endif()
string(FIND "${MW}" "setRouterConnectionCollapsed" POS)
if(POS EQUAL -1)
  message(FATAL_ERROR "connection collapse remains a direct user action")
endif()
message(STATUS "Batch44 workspace behavior contract superseded by Batch48 and passed")
