set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
function(req path needle message_text)
  file(READ "${ROOT}/${path}" TEXT)
  string(FIND "${TEXT}" "${needle}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Batch49: ${message_text}: missing '${needle}' in ${path}")
  endif()
endfunction()
function(forbid path needle message_text)
  file(READ "${ROOT}/${path}" TEXT)
  string(FIND "${TEXT}" "${needle}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Batch49: ${message_text}: found forbidden '${needle}' in ${path}")
  endif()
endfunction()

req("MainWindow.ui" "<string>导入日志</string>" "offline button must be plain log import")
forbid("MainWindow.ui" "导入日志/配置" "configuration import wording must be removed")
req("MainWindow.cpp" "日志文件 (*.txt *.log)" "log picker must only expose text/log files")
forbid("MainWindow.cpp" "日志/配置文件 (*.txt *.log *.bin)" "bin configuration picker must be removed")
forbid("MainWindow.cpp" "NvramSnapshotParser::parse(bytes)" "offline UI must not parse configuration snapshots")
req("MainWindow.cpp" "*.pcap *.cap *.pcapng" "capture picker must expose pcap/cap/pcapng")
req("capture/OfflinePcapController.cpp" "0A0D0D0A" "offline loader must detect pcapng by content")
req("capture/OfflinePcapController.cpp" "Enhanced Packet Block" "pcapng enhanced packets must be parsed")
req("tests/test_offlinepcapcontroller.cpp" "loadsPcapngEnhancedPacket" "pcapng parser needs a real regression test")
req("CMakeLists.txt" "resources/app_icon.rc" "Windows executable must embed an icon")
req("CMakeLists.txt" "resources/app_icon.qrc" "Qt application/window icon resource must be linked")
req("main.cpp" "setWindowIcon" "application must set the runtime window/taskbar icon")
req("resources/app_icon.rc" "IDI_APP_ICON ICON" "Windows resource script must embed ico")
req("resources/app_icon.qrc" "fourfaith_routerdiag.ico" "Qt resources must expose the icon")
req("tests/CMakeLists.txt" "test_batch49_offline_import_icon_contract" "Batch49 contract must be registered")
message(STATUS "Batch49 offline import/icon contract passed")
