set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")

function(require_file path)
  if(NOT EXISTS "${ROOT}/${path}")
    message(FATAL_ERROR "Batch33: missing ${path}")
  endif()
endfunction()

function(require_contains path needle)
  file(READ "${ROOT}/${path}" TEXT)
  string(FIND "${TEXT}" "${needle}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Batch33: ${path} missing: ${needle}")
  endif()
endfunction()

function(require_not_contains path needle)
  file(READ "${ROOT}/${path}" TEXT)
  string(FIND "${TEXT}" "${needle}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Batch33: ${path} still contains forbidden fixed-size pattern: ${needle}")
  endif()
endfunction()

require_file("ui/DetachablePanelManager.h")
require_file("ui/DetachablePanelManager.cpp")
require_contains("ui/DetachablePanelManager.h" "class DetachablePanelManager")
require_contains("ui/DetachablePanelManager.cpp" "QSettings")
require_contains("ui/DetachablePanelManager.cpp" "detachPanel")
require_contains("ui/DetachablePanelManager.cpp" "reattachPanel")
require_contains("MainWindow.cpp" "setupResizableWorkspace")
require_contains("MainWindow.cpp" "packetStatsSplitter")
require_contains("MainWindow.cpp" "实时抓包：报文与统计")
require_contains("MainWindow.cpp" "实时抓包：包详情")
require_contains("MainWindow.cpp" "Ping 实时结果")
require_contains("MainWindow.cpp" "网口详情")
require_contains("MainWindow.cpp" "实时运行日志")
require_contains("MainWindow.cpp" "workspace/packetVerticalSplitter")
require_contains("MainWindow.cpp" "workspace/diagnosisSplitter")
require_not_contains("ui/CaptureSessionWidget.cpp" "setMaximumHeight(130)")
require_contains("ui/CaptureSessionWidget.cpp" "QSplitter")
require_contains("ui/CaptureSessionWidget.cpp" "DetachablePanelManager")
require_contains("ui/RemoteToolDialog.cpp" "QSplitter")
require_contains("CMakeLists.txt" "ui/DetachablePanelManager.cpp")
require_contains("tests/CMakeLists.txt" "../ui/DetachablePanelManager.cpp")
require_contains("tests/CMakeLists.txt" "test_batch33_resizable_floating_workspace_contract")
message(STATUS "Batch33 resizable/floating workspace contract passed")
