cmake_minimum_required(VERSION 3.16)
set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
file(READ "${ROOT}/MainWindow.h" MAIN_H)
file(READ "${ROOT}/MainWindow.cpp" MAIN_CPP)

function(req text needle msg)
  string(FIND "${text}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "${msg}: missing [${needle}]")
  endif()
endfunction()

req("${MAIN_H}" "void abortRouterConnectionAttempt(const QString& reason);" "MainWindow needs one cleanup path for failed router connection/login")
req("${MAIN_H}" "bool m_routerConnectInProgress=false;" "MainWindow must distinguish initial login from established-session failures")
req("${MAIN_H}" "QString m_routerConnectionFailureMessage;" "failure text must survive asynchronous disconnected signals")
req("${MAIN_CPP}" "void MainWindow::abortRouterConnectionAttempt(const QString& reason)" "failed login must close all partial router transports")
req("${MAIN_CPP}" "登录/连接失败，已自动断开" "UI must tell the operator that cleanup was automatic")
req("${MAIN_CPP}" "connect(m_control,&TelnetClient::loginFailed" "control login failure handler must exist")
req("${MAIN_CPP}" "abortRouterConnectionAttempt(QStringLiteral(\"控制连接登录失败：%1\").arg(e))" "control login failure must auto-disconnect")
req("${MAIN_CPP}" "connect(m_capture,&TelnetClient::loginFailed" "capture login failure handler must exist")
req("${MAIN_CPP}" "if(m_routerConnectInProgress)" "initial secondary-session failure must be distinguished from later workflow reconnect failure")
req("${MAIN_CPP}" "abortRouterConnectionAttempt(QStringLiteral(\"抓包连接登录失败：%1\").arg(e))" "initial capture login failure must auto-disconnect")
req("${MAIN_CPP}" "if(m_routerConnectInProgress && !m_routerDisconnectRequested)" "connection-stage transport errors/disconnects must trigger cleanup")
req("${MAIN_CPP}" "m_routerConnectionFailureMessage.clear();" "a new/manual connection cycle must clear stale failure text")

message(STATUS "Batch29 auto-disconnect login failure contract passed")
