cmake_minimum_required(VERSION 3.16)
set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
file(READ "${ROOT}/diagnostic/DeviceDiscoveryController.h" HDR)
file(READ "${ROOT}/diagnostic/DeviceDiscoveryController.cpp" CPP)
file(READ "${ROOT}/MainWindow.cpp" MAIN)
file(READ "${ROOT}/MainWindow.ui" UI)
file(READ "${ROOT}/diagnostic/DiagnosisEngine.cpp" ENGINE)
file(READ "${ROOT}/report/ReportExporter.cpp" REPORT)

function(require_contains text needle message)
  string(FIND "${text}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "${message}: missing [${needle}]")
  endif()
endfunction()

function(require_not_contains text needle message)
  string(FIND "${text}" "${needle}" pos)
  if(NOT pos EQUAL -1)
    message(FATAL_ERROR "${message}: forbidden [${needle}]")
  endif()
endfunction()

require_contains("${HDR}" "moduleControlDevice" "device discovery must expose the responsive AT device")
require_contains("${HDR}" "moduleManufacturer" "device discovery must expose module manufacturer")
require_contains("${HDR}" "moduleModel" "device discovery must expose module model")
require_contains("${HDR}" "moduleFirmware" "device discovery must expose module firmware")
require_contains("${CPP}" "command -v at_test" "module probe must prefer at_test when available")
require_contains("${CPP}" "grep -q '^[[:space:]]*OK[[:space:]]*$'" "at_test output without a whitespace-tolerant OK line must fall back to direct device access")
require_contains("${CPP}" "/dev/ttyUSB*" "module probe must discover ttyUSB candidates")
require_contains("${CPP}" "/dev/ttyACM*" "module probe must discover ttyACM candidates")
require_contains("${CPP}" [=[printf '%s\\r\\n']=] "direct AT fallback must send CRLF safely")
require_contains("${CPP}" [=[cat \"$dev\"]=] "direct AT fallback must read the device")
require_contains("${CPP}" [=[kill \"$pid\"]=] "direct AT fallback must terminate its background reader")
require_contains("${CPP}" "QStringLiteral(\"ATI\")" "module probe must query ATI")
require_contains("${CPP}" "QStringLiteral(\"AT+CGMI\")" "module probe must query manufacturer")
require_contains("${CPP}" "QStringLiteral(\"AT+CGMM\")" "module probe must query model")
require_contains("${CPP}" "QStringLiteral(\"AT+CGMR\")" "module probe must query firmware")
require_contains("${MAIN}" "QStringLiteral(\"模组\")" "module card must use the concise name")
require_not_contains("${MAIN}" "蜂窝模组" "MainWindow must not show the old module name")
require_not_contains("${UI}" "蜂窝模组" "UI must not show the old module name")
require_not_contains("${ENGINE}" "蜂窝模组" "diagnosis conclusions must not show the old module name")
require_not_contains("${REPORT}" "蜂窝模组" "reports must not show the old module name")
message(STATUS "Batch23 module probe fallback contract passed")
