set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
function(require_contains path needle)
  file(READ "${ROOT}/${path}" TEXT)
  string(FIND "${TEXT}" "${needle}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Batch36 RC13 reliability: ${path} missing: ${needle}")
  endif()
endfunction()
require_contains("diagnostic/AtStatusParser.h" "QList<bool> fieldQuoted")
require_contains("diagnostic/DiagnosticTypes.h" "moduleProbeAttempted")
require_contains("diagnostic/DiagnosisEngine.cpp" "primaryRegistration")
require_contains("diagnostic/ChannelAnalyzer.h" "actualPeerSessions")
require_contains("diagnostic/ChannelAnalyzer.cpp" "业务完成后连接被重置")
require_contains("diagnostic/DualCaptureCorrelator.h" "rangeMatchedPackets")
require_contains("diagnostic/DualCaptureCorrelator.cpp" "sequenceRangeOverlap")
require_contains("protocol/ProtocolDiagnosis.h" "responseExpected")
require_contains("ui/RemoteToolDialog.cpp" "CategoryRole")
require_contains("ui/RemoteToolDialog.cpp" "editQuickCommandSearch")
require_contains("ui/RemoteToolDialog.cpp" "iptables -t nat -L -n -v")
require_contains("ui/RemoteToolDialog.cpp" "nvram set debuglog_enable=1; nvram commit")
require_contains("MainWindow.cpp" "setRouterConnectionCollapsed")
require_contains("MainWindow.cpp" "refreshCaptureQuickFilter")
require_contains("MainWindow.ui" "editCaptureQuickSearch")
require_contains("tests/CMakeLists.txt" "test_batch36_rc13_reliability_contract")
require_contains("MainWindow.cpp" "btnToggleRouterConnectionCollapsed")

message(STATUS "Batch36 RC13 reliability contract passed")
