cmake_minimum_required(VERSION 3.16)
set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
file(READ "${ROOT}/CMakeLists.txt" CMAKE_TEXT)
file(READ "${ROOT}/telnet/TelnetClient.h" TELNET_H)
file(READ "${ROOT}/telnet/TelnetClient.cpp" TELNET_CPP)
file(READ "${ROOT}/MainWindow.h" MAIN_H)
file(READ "${ROOT}/MainWindow.cpp" MAIN_CPP)
file(READ "${ROOT}/MainWindow.ui" UI)
file(READ "${ROOT}/capture/PacketCaptureController.cpp" CAPTURE_CPP)
file(READ "${ROOT}/capture/PacketCaptureController.h" CAPTURE_H)
file(READ "${ROOT}/package_onefile_release.bat" PACKAGE_FULL)
file(READ "${ROOT}/package_onefile_release_lite.bat" PACKAGE_LITE)

function(require_contains text needle message)
  string(FIND "${text}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "${message}: missing [${needle}]")
  endif()
endfunction()

require_contains("${CMAKE_TEXT}" "SerialPort" "router serial transport must link Qt SerialPort")
require_contains("${TELNET_H}" "connectToSerial" "TelnetClient must expose a serial-console transport")
require_contains("${TELNET_H}" "QSerialPort" "TelnetClient must own a Qt serial port")
require_contains("${TELNET_CPP}" "m_serial.write(\"\\r\")" "opening the router serial console must send one carriage return")
require_contains("${TELNET_H}" "QSerialPort::NoFlowControl" "router serial console must default to no flow control")
require_contains("${UI}" "comboRouterConnectionMode" "router connection UI must choose network or serial")
require_contains("${UI}" "comboPcSerialPort" "router connection UI must expose detected PC serial ports")
require_contains("${UI}" "btnRefreshSerialPorts" "router connection UI must allow serial-port refresh")
require_contains("${UI}" "comboSerialBaud" "router connection UI must expose baud rate")
require_contains("${UI}" "<string>115200</string>" "router serial baud rate must default to 115200")
require_contains("${UI}" "comboSerialDataBits" "router connection UI must expose data bits")
require_contains("${UI}" "comboSerialStopBits" "router connection UI must expose stop bits")
require_contains("${UI}" "comboSerialParity" "router connection UI must expose parity")
require_contains("${MAIN_H}" "refreshSerialPorts" "MainWindow must support automatic PC serial enumeration")
require_contains("${MAIN_CPP}" "QSerialPortInfo::availablePorts()" "PC serial ports must be enumerated from the OS")
require_contains("${MAIN_CPP}" "connectToSerial" "serial mode must open the selected PC serial port")
require_contains("${MAIN_CPP}" "refreshSerialPorts();" "serial ports must be refreshed automatically")
require_contains("${CAPTURE_H}" "setSingleSession" "serial router mode must reuse the logged-in console for capture")
require_contains("${CAPTURE_CPP}" "buildTextTcpdumpCommand" "single serial console capture must avoid raw binary PTY mode")
require_contains("${CAPTURE_CPP}" "sendInterrupt" "serial tcpdump must be stoppable on the shared console")
require_contains("${PACKAGE_FULL}" "Qt6SerialPort.dll" "full one-file package must verify the Qt serial runtime")
require_contains("${PACKAGE_LITE}" "Qt6SerialPort.dll" "lite one-file package must verify the Qt serial runtime")
message(STATUS "Batch24 router serial connection contract passed")
