cmake_minimum_required(VERSION 3.16)
set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
file(READ "${ROOT}/MainWindow.cpp" main)
file(READ "${ROOT}/MainWindow.h" header)
function(require_contains text needle label)
  string(FIND "${text}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "Batch32 missing ${label}: ${needle}")
  endif()
endfunction()
function(require_not_contains text needle label)
  string(FIND "${text}" "${needle}" pos)
  if(NOT pos EQUAL -1)
    message(FATAL_ERROR "Batch32 still contains ${label}: ${needle}")
  endif()
endfunction()
# Batch48 intentionally normalizes the compact card face to plain state text;
# structured registration parsing still feeds DiagnosisEngine/layer state instead of raw AT text on the card.
require_contains("${main}" "cardStateText(registrationLayer.state)" "normalized registration layer state in status card")
require_not_contains("${main}" "parts.last().trimmed().toInt" "old last-field registration parser")
require_contains("${main}" "m_tcpReassembler.reset()" "TCP stream reset between capture/replay sessions")
require_contains("${main}" "m_protocolRefreshTimer->setInterval(200)" "coalesced protocol refresh")
require_contains("${main}" "!m_protocolRefreshTimer->isActive()" "protocol rebuild burst coalescing")
require_contains("${main}" "!m_tcpReassembler.directions().isEmpty()" "final protocol rebuild on stop")
require_contains("${header}" "m_protocolRefreshTimer" "protocol refresh timer member")
message(STATUS "Batch32 realtime parser/state contract passed")
