set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
function(require_contains path needle)
  file(READ "${ROOT}/${path}" TEXT)
  string(FIND "${TEXT}" "${needle}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Batch41: ${path} missing: ${needle}")
  endif()
endfunction()

require_contains("MainWindow.cpp" "width>=1440")
require_contains("MainWindow.cpp" "fieldAdvancedPanel")
require_contains("MainWindow.cpp" "btnToggleFieldAdvanced")
require_contains("MainWindow.cpp" "btnToggleLayerDetail")
require_contains("MainWindow.cpp" "QAbstractSpinBox::NoButtons")
require_contains("MainWindow.cpp" "ui->diagnosisSplitter->setSizes({540,660})")
require_contains("MainWindow.cpp" "setCompactHeader(compact)")
require_contains("ui/DetachablePanelManager.cpp" "detachablePanelHint")
require_contains("ui/DetachablePanelManager.cpp" "setCompactHeader")
require_contains("tests/test_mainwindowui.cpp" "compact1280UsesManagedFieldLayoutAndAdvancedPanel")
require_contains("tests/test_mainwindowui.cpp" "compactLayerDetailStartsCollapsedAndCanExpandOnDemand")
require_contains("tests/CMakeLists.txt" "test_batch41_1280_layout_contract")
message(STATUS "Batch41 1280 layout contract passed")
