set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
function(require_contains path needle)
  file(READ "${ROOT}/${path}" TEXT)
  string(FIND "${TEXT}" "${needle}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Batch40: ${path} missing: ${needle}")
  endif()
endfunction()
function(require_not_contains path needle)
  file(READ "${ROOT}/${path}" TEXT)
  string(FIND "${TEXT}" "${needle}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Batch40: ${path} must not contain: ${needle}")
  endif()
endfunction()

require_contains("MainWindow.cpp" "compactConnectionBar")
require_contains("MainWindow.cpp" "btnCompactConnect")
require_contains("MainWindow.cpp" "btnCompactDisconnect")
require_contains("MainWindow.cpp" "btnCompactExpandConnection")
require_contains("MainWindow.cpp" "setMaximumHeight(collapsed?72:QWIDGETSIZE_MAX)")
require_contains("tests/test_mainwindowui.cpp" "routerConnectionCollapseUsesSingleCompactRow")
require_contains("MainWindow.cpp" "四信路由器通信诊断工具")
require_contains("MainWindow.ui" "四信路由器通信诊断工具")
require_contains("main.cpp" "四信路由器通信诊断工具")
require_contains("report/ReportExporter.cpp" "四信路由器通信诊断工具")
require_contains("README.md" "四信路由器通信诊断工具")
require_not_contains("MainWindow.cpp" "四信路由通信智能诊断工具")
require_not_contains("MainWindow.ui" "四信路由通信智能诊断工具")
require_not_contains("main.cpp" "四信路由通信智能诊断工具")
require_not_contains("report/ReportExporter.cpp" "四信路由通信智能诊断工具")
require_contains("tests/CMakeLists.txt" "test_batch40_compact_connection_branding_contract")
message(STATUS "Batch40 compact connection and branding contract passed")
