cmake_minimum_required(VERSION 3.16)
set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
function(read_file rel out)
  file(READ "${ROOT}/${rel}" _text)
  set(${out} "${_text}" PARENT_SCOPE)
endfunction()
function(require_contains text needle message)
  string(FIND "${text}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "${message}: missing [${needle}]")
  endif()
endfunction()

read_file("diagnostic/DeviceDiscoveryController.cpp" discovery)
require_contains("${discovery}" "nvram get bkup_wan_ipaddr" "device discovery must query backup WAN IP")
require_contains("${discovery}" "wanIpSource" "device discovery must preserve WAN IP source")

read_file("diagnostic/LogAnalyzer.cpp" loganalyzer)
require_contains("${loganalyzer}" "bkup_wan_ipaddr" "log analyzer must parse backup WAN IP")

read_file("diagnostic/ConnectivityProbe.h" ping_h)
require_contains("${ping_h}" "rawOutput" "PingResult must retain raw output")
require_contains("${ping_h}" "packetLossPercent" "PingResult must retain packet loss")
require_contains("${ping_h}" "avgRttMs" "PingResult must retain RTT summary")

read_file("diagnostic/FieldDiagnosticController.h" field_h)
require_contains("${field_h}" "pingOutputReceived" "field ping must stream raw output")

read_file("MainWindow.ui" ui)
require_contains("${ui}" "groupPingResult" "field diagnosis must contain a ping result panel")
require_contains("${ui}" "txtPingResult" "ping panel must show raw output")
require_contains("${ui}" "labelPingResultSummary" "ping panel must show parsed summary")

read_file("MainWindow.cpp" mw)
require_contains("${mw}" "narrow" "main window must have a narrow responsive layout mode")
require_contains("${mw}" "bkup_wan_ipaddr" "main window must surface backup WAN IP source")
require_contains("${mw}" "tcpPayloadLength" "packet list must use TCP payload length for TCP")
require_contains("${mw}" "当前暂无匹配流量" "capture UI must distinguish running with zero matching packets")
require_contains("${mw}" "pingOutputReceived" "main window must render live ping output")

read_file("MainWindow.ui" ui2)
require_contains("${ui2}" "<width>800</width>" "minimum window width should allow a smaller field layout")

read_file("telnet/TelnetClient.h" telnet_h)
require_contains("${telnet_h}" "isBusy()" "shared control Telnet must expose busy state")
read_file("capture/PacketCaptureController.cpp" capture_ctrl)
require_contains("${capture_ctrl}" "控制 Telnet 正在执行其他命令" "capture start must report control-channel contention")
read_file("diagnostic/ChannelAnalyzer.cpp" channel)
require_contains("${channel}" "不能仅凭Ping判定终端不可达" "terminal Ping-only failure must remain conservative")
read_file("ui/RemoteToolDialog.cpp" remote)
require_contains("${remote}" "Ping完成：接收" "Ping tool must show parsed summary after streaming raw output")
read_file("diagnostic/DiagnosisEngine.cpp" engine)
require_contains("${engine}" "RSRP覆盖功率尚可，但SINR偏低" "signal assessment must combine RSRP and SINR")
require_contains("${mw}" "WAN尚未具备有效测试条件" "master transport must respect upstream WAN blocking")
require_contains("${mw}" "WAN抓包默认带入已确认WAN" "WAN capture mode must default to detected WAN interface while allowing explicit capture-interface override")

if(NOT EXISTS "${ROOT}/capture/TcpStreamReassembler.cpp")
  message(FATAL_ERROR "TCP stream reassembler implementation missing")
endif()
read_file("MainWindow.cpp" mw_stream)
require_contains("${mw_stream}" "m_tcpReassembler" "business analysis must use TCP stream reassembly")

message(STATUS "Batch18 contract passed")
