cmake_minimum_required(VERSION 3.16)
set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
file(READ "${ROOT}/MainWindow.cpp" C)
function(require_contains text needle message)
  string(FIND "${text}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "${message}: missing [${needle}]")
  endif()
endfunction()
function(require_not_contains text needle message)
  string(FIND "${text}" "${needle}" pos)
  if(NOT pos EQUAL -1)
    message(FATAL_ERROR "${message}: forbidden [${needle}]")
  endif()
endfunction()
require_contains("${C}" "hasWan?result.wanIfname:QStringLiteral(\"未识别\")" "discovery WAN card must show only interface or 未识别")
require_contains("${C}" "wanInventoryAttempted?QStringLiteral(\"未识别\"):cardStateText(wanLayer.state)" "diagnosis WAN card must distinguish attempted-but-unrecognized from never tested")
require_not_contains("${C}" "!wanIface.isEmpty()?wanIface:layerStateText(wanLayer.state)" "WAN card must not fall back to diagnosis state text")
message(STATUS "Batch20 WAN interface card contract passed")
