cmake_minimum_required(VERSION 3.16)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
function(require_contains file needle message_text)
  file(READ "${ROOT}/${file}" content)
  string(FIND "${content}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "Batch43 contract: ${message_text} (${needle})")
  endif()
endfunction()
require_contains("MainWindow.cpp" "新建抓包窗口" "capture task action must use the finalized label")
require_contains("MainWindow.cpp" "btnNewCaptureWindow" "capture workspace must keep a visible new-window action")
require_contains("MainWindow.cpp" "ui->labelTerminalRole->setVisible(ethernet)" "serial terminal mode must hide terminal role")
require_contains("MainWindow.cpp" "fieldAdvancedPanel->show()" "field advanced parameters must remain visible")
require_contains("ui/RemoteToolDialog.cpp" "重启路由器" "quick commands must include reboot")
require_contains("ui/RemoteToolDialog.cpp" "查看模组和信号" "quick commands must include field module summary")
require_contains("tests/test_mainwindowui.cpp" "realtimeCaptureNewTaskLivesInPanelHeader" "UI regression must cover capture header action")
require_contains("tests/test_remotetooldialog.cpp" "foundReboot" "quick command regression must cover reboot")
message(STATUS "Batch43 capture/serial/quick-command contract passed")
