set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
function(require_contains path needle)
  file(READ "${ROOT}/${path}" TEXT)
  string(FIND "${TEXT}" "${needle}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Batch34: ${path} missing: ${needle}")
  endif()
endfunction()
require_contains("MainWindow.cpp" "addPanel(ui->diagnosisDetailTabs")
require_contains("MainWindow.cpp" "现场诊断：详情与报告")
require_contains("MainWindow.cpp" "diagnosisDetails")
require_contains("tests/CMakeLists.txt" "test_batch34_diagnosis_detail_floating_contract")
message(STATUS "Batch34 diagnosis detail floating contract passed")
