cmake_minimum_required(VERSION 3.16)
set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
file(READ "${ROOT}/capture/PacketCaptureController.cpp" C)
function(require_contains text needle message)
  string(FIND "${text}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "${message}: missing [${needle}]")
  endif()
endfunction()
function(require_not_contains text needle message)
  string(FIND "${text}" "${needle}" pos)
  if(NOT pos EQUAL -1)
    message(FATAL_ERROR "${message}: forbidden [${needle}]")
  endif()
endfunction()
require_not_contains("${C}" "tcpdump -i %1 -d" "embedded tcpdump preflight must not depend on -d")
require_contains("${C}" "/tmp/wandiag_tcpdump.err" "tcpdump stderr must be preserved outside PCAP stream")
require_contains("${C}" "stty raw -echo" "capture Telnet must enter raw/no-echo mode before binary PCAP")
require_contains("${C}" "m_capturePrepCommand" "capture startup must wait for capture-session preparation")
require_contains("${C}" "m_errorProbeCommand" "startup timeout must retrieve router tcpdump stderr")
message(STATUS "Batch19 capture contract passed")
