set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
function(require_contains path needle)
  file(READ "${ROOT}/${path}" TEXT)
  string(FIND "${TEXT}" "${needle}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Batch37: ${path} missing: ${needle}")
  endif()
endfunction()
function(require_not_contains path needle)
  file(READ "${ROOT}/${path}" TEXT)
  string(FIND "${TEXT}" "${needle}" POS)
  if(NOT POS EQUAL -1)
    message(FATAL_ERROR "Batch37: ${path} must not contain: ${needle}")
  endif()
endfunction()

require_contains("diagnostic/NvramSnapshotParser.h" "FourFaithBinary")
require_contains("diagnostic/NvramSnapshotParser.cpp" "FOUR-FAITH:")
require_contains("diagnostic/NvramSnapshotParser.cpp" "valueLength")
require_contains("diagnostic/NvramSnapshotParser.cpp" "isSensitiveKey")
require_contains("diagnostic/LogAnalyzer.h" "analyzeNvramSnapshot")
require_contains("diagnostic/LogAnalyzer.cpp" "activeWanPath")
# Batch51: explicit WAN NVRAM hints must outrank the default route when ifconfig confirms them;
# the route remains a fallback only when those hints cannot identify a real interface.
require_contains("diagnostic/DeviceDiscoveryController.cpp" "Default route is only a fallback after ifconfig + NVRAM")
require_contains("diagnostic/DeviceDiscoveryController.cpp" "r.wanIfname=r.defaultRouteInterface")
require_contains("diagnostic/DeviceDiscoveryController.cpp" "selectedHint=QStringLiteral(\"默认路由\")")
require_contains("diagnostic/DiagnosticTypes.h" "nvramSnapshotPresent")
require_contains("diagnostic/DiagnosticTypes.h" "moduleIdentityMismatch")
require_contains("diagnostic/DiagnosticTypes.h" "dtsDcuConStatus2")
require_contains("diagnostic/LogAnalyzer.cpp" "dts_dcu_con_status_2")
require_contains("diagnostic/DiagnosisEngine.cpp" "配置快照")
# Batch49 removed configuration-file import from the UI; parser remains available and unit-tested for historical/backend compatibility.
require_not_contains("MainWindow.cpp" "NvramSnapshotParser::parse(bytes)")
# A later live discovery/log result must supersede offline snapshot provenance.
require_contains("MainWindow.cpp" "wanIpFromNvramSnapshot=false")
require_contains("MainWindow.cpp" "simStatusFromNvram=false")
require_contains("MainWindow.cpp" "defaultRouteChecked=result.defaultRouteChecked")
require_contains("MainWindow.cpp" "wanInterfaceStateKnown=result.wanInterfaceStateKnown")
require_contains("MainWindow.ui" "<string>导入日志</string>")
require_not_contains("MainWindow.ui" "导入日志/配置")
require_contains("CMakeLists.txt" "diagnostic/NvramSnapshotParser.cpp")
require_contains("tests/CMakeLists.txt" "test_nvramsnapshotparser")
require_contains("tests/CMakeLists.txt" "test_batch37_field_config_snapshot_contract")
# Never log/dump the full imported snapshot: it may contain passwords, keys, IMSI/IMEI/ICCID and credentials.
require_not_contains("MainWindow.cpp" "snapshot.toText()")
message(STATUS "Batch37 field config snapshot contract passed")
