cmake_minimum_required(VERSION 3.16)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
function(read_file rel out)
  file(READ "${ROOT}/${rel}" content)
  set(${out} "${content}" PARENT_SCOPE)
endfunction()
function(req hay needle msg)
  string(FIND "${hay}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "Batch56 contract failed: ${msg}: missing [${needle}]")
  endif()
endfunction()
function(forbid hay needle msg)
  string(FIND "${hay}" "${needle}" pos)
  if(NOT pos EQUAL -1)
    message(FATAL_ERROR "Batch56 contract failed: ${msg}: found forbidden [${needle}]")
  endif()
endfunction()
read_file("telnet/TelnetClient.h" TH)
read_file("telnet/TelnetClient.cpp" TC)
read_file("MainWindow.cpp" MW)
read_file("MainWindow.h" MH)
read_file("ui/RemoteToolDialog.cpp" RT)
read_file("ui/CaptureSessionWidget.h" CSH)
read_file("ui/CaptureSessionWidget.cpp" CSC)
read_file("diagnostic/FieldDiagnosticController.cpp" FD)
read_file("diagnostic/DeviceDiscoveryController.cpp" DD)
read_file("diagnostic/DeviceDiscoveryController.h" DH)
read_file("diagnostic/DiagnosisEngine.cpp" DE)
read_file("capture/OfflinePcapController.cpp" OP)
read_file("capture/OfflinePcapController.h" OH)
read_file("tests/test_mainwindowui.cpp" TMW)

# User-visible command streams must hide wrapper commands, completion markers and prompts everywhere.
req("${TH}" "visibleTextReceived" "Telnet client must expose globally cleaned visible text")
req("${TC}" "sanitizeVisibleLine" "visible text must filter wrapper/marker/prompt lines")
req("${TC}" "m_visibleLineBuffer" "streaming sanitizer must handle command echoes split across chunks")
req("${FD}" "visibleTextReceived" "Ping live output must use cleaned visible stream")
req("${RT}" "visibleTextReceived" "tool windows must use cleaned visible stream")
req("${MW}" "visibleTextReceived" "main visible serial/module-log windows must use cleaned visible stream")

# Capture mode and interface must stay aligned. `any` is the one tcpdump pseudo-interface exception.
req("${MW}" "names<<QStringLiteral(\"any\")" "main capture interface list must include any")
req("${CSC}" "QStringLiteral(\"any\")" "detached capture window must retain any")
req("${MW}" "setCaptureInterfaceText(autoTerminalCaptureInterface())" "terminal mode must map to terminal-side interface")
req("${MW}" "if(ethernet && ui->comboCaptureMode->currentIndex()==2)setCaptureInterfaceText(autoTerminalCaptureInterface());" "switching terminal transport back to Ethernet must realign terminal capture interface")
req("${MW}" "setCaptureInterfaceText(detectedWan)" "WAN/master modes must map to detected WAN")
req("${TMW}" "captureInterfaceSelectorIncludesAnyPseudoInterface" "Qt UI test must cover any pseudo-interface")

# Synchronized workflow capture gets the existing main ifconfig inventory and must not race an extra refresh.
req("${CSH}" "autoRefreshInterfaces" "capture session params must control automatic interface refresh")
req("${CSC}" "if(m_params.autoRefreshInterfaces)" "constructor refresh must be suppressible")
req("${MW}" "createCaptureSessionWindow" "workflow must create dedicated sessions")
req("${MW}" "false,false" "synchronized sessions must suppress redundant interface refresh")

# NVRAM fast path and backup-card selection. Interface inventory remains ordinary ifconfig UP-only.
req("${DD}" "this_is_bkup" "device discovery must read active main/backup card flag")
req("${DD}" "buildFastNvramCommand" "NVRAM scalar reads must be batched into one control round-trip")
req("${DD}" "bkup_current_module_real_name" "backup-card module identity must be supported")
req("${DD}" "comm_rsrp" "main-card RSRP must come from NVRAM when available")
req("${DD}" "comm_sinr" "main-card SINR must come from NVRAM when available")
req("${DD}" "QStringLiteral(\"ifconfig 2>/dev/null\")" "interface inventory must remain ordinary ifconfig")
req("${DH}" "commModuleStatus" "fast NVRAM module runtime status must reach discovery result")
req("${DH}" "commDialStatus" "fast NVRAM dial status must reach discovery result")
req("${DH}" "nvramFirmware" "fast NVRAM module firmware must reach discovery result")
req("${DE}" "NVRAM实时状态显示蜂窝数据已入网" "live fast-NVRAM dial/network evidence should populate registration without waiting for AT")
req("${DE}" "NVRAM实时状态显示模组工作中" "live fast-NVRAM module status should populate module layer without waiting for AT")

# Large PCAP import: streaming/chunked, bounded visible rows, import immediately analyzes/displays.
forbid("${OP}" "return loadData(f.readAll(),error,path);" "loadFile must not read whole PCAP into memory")
req("${OP}" "ChunkSize" "large PCAP must be consumed in chunks")
req("${OH}" "loadProgress" "large PCAP import must expose progress")
req("${OH}" "replayAvailable" "large PCAP may disable replay cache while retaining direct analysis")
req("${MH}" "m_offlineBulkImport" "main window must have bulk-import UI throttling state")
req("${MW}" "MaxOfflineVisiblePackets=20000" "offline table must stay bounded to 20k visible packets")
req("${MW}" "renderOfflineRecentPackets" "import must directly render parsed packets")
req("${MW}" "PCAP 已导入并分析" "plain PCAP import must complete analysis/display without requiring replay")

# Terminal Ethernet validation: configured terminal IP must share a subnet with br0 or br0:1 from ifconfig.
req("${DH}" "QString netmask" "ifconfig interface inventory must retain IPv4 netmask")
req("${MW}" "validateTerminalLanSubnet" "terminal Ethernet checks must validate br0/br0:1 subnet before probing")
req("${MW}" "终端IP配置错误，请检查配置" "subnet mismatch must produce an explicit configuration-error prompt")
req("${MW}" "info.name!=QStringLiteral(\"br0\") && info.name!=QStringLiteral(\"br0:1\")" "terminal subnet validation must only use br0/br0:1")
req("${MW}" "sameIpv4Subnet(terminalIp,info.ipv4,info.netmask)" "terminal interface selection must use the terminal IP subnet")
req("${MW}" "iface=autoTerminalCaptureInterface();" "workflow terminal capture must not hard-code br0")
req("${MW}" "startFieldCapture(FieldCaptureMode::TerminalEthernet,autoTerminalCaptureInterface()" "manual terminal capture must use the matching LAN interface")

message(STATUS "Batch56 fast-NVRAM/capture-any/clean-output/large-PCAP/terminal-subnet contract passed")
