cmake_minimum_required(VERSION 3.16)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(MW "${ROOT}/MainWindow.cpp")
set(MH "${ROOT}/MainWindow.h")

function(req file needle message)
  file(READ "${file}" content)
  string(FIND "${content}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "${message}: missing [${needle}] in ${file}")
  endif()
endfunction()

req("${MW}" "fieldSummaryPanel" "现场诊断首屏必须提供运维摘要面板")
req("${MW}" "当前阶段" "现场摘要必须给出当前阶段")
req("${MW}" "下一步建议" "现场摘要必须给出处置方向")
req("${MW}" "packetMatchesCaptureQuickFilter" "抓包筛选逻辑必须集中到可复用匹配函数")
req("${MW}" "packet.payload.toHex(' ')" "快速搜索必须支持HEX内容")
req("${MH}" "updateFieldSummary" "主窗口必须声明现场摘要刷新函数")
message(STATUS "Batch57 field operations UI contract passed")
