cmake_minimum_required(VERSION 3.16)
set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
file(READ "${ROOT}/MainWindow.cpp" MW)
file(READ "${ROOT}/MainWindow.ui" UI)
file(READ "${ROOT}/ui/RemoteToolDialog.cpp" RT)

function(req text needle message)
  string(FIND "${text}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "Batch46 contract failed: ${message} (missing: ${needle})")
  endif()
endfunction()
function(forbid text needle message)
  string(FIND "${text}" "${needle}" pos)
  if(NOT pos EQUAL -1)
    message(FATAL_ERROR "Batch46 contract failed: ${message} (found forbidden: ${needle})")
  endif()
endfunction()

req("${UI}" "name=\"comboCaptureInterface\"" "capture interface selector must be defined in MainWindow.ui")
req("${UI}" "name=\"btnRefreshCaptureInterfaces\"" "capture interface refresh button must be defined in MainWindow.ui")
forbid("${MW}" "ui->editIface" "removed editIface member must never be referenced after Batch45 UI migration")
req("${MW}" "m_captureIfaceCombo=ui->comboCaptureInterface" "MainWindow must reuse the UI-defined editable interface combo")
req("${MW}" "m_refreshCaptureIfaces=ui->btnRefreshCaptureInterfaces" "MainWindow must reuse the UI-defined refresh button")

string(FIND "${RT}" "beginReadArray(QStringLiteral(\"remoteCommands/custom\"))" customPos)
string(FIND "${RT}" "for(const auto& item:builtins)addCommandItem" builtinPos)
if(customPos EQUAL -1 OR builtinPos EQUAL -1 OR NOT customPos LESS builtinPos)
  message(FATAL_ERROR "Batch46 contract failed: persisted custom quick commands must load before built-ins so same-name user entries stay selectable")
endif()
req("${RT}" "QStringLiteral(\"查看进程\"),QStringLiteral(\"ps\")" "ps must remain a built-in read-only quick command")
req("${RT}" "QStringLiteral(\"重启路由器\"),QStringLiteral(\"reboot\")" "reboot must remain a maintenance quick command")

message(STATUS "Batch46 Windows compile + quick-command contract passed")
