cmake_minimum_required(VERSION 3.16)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
function(read_file rel out)
  file(READ "${ROOT}/${rel}" content)
  set(${out} "${content}" PARENT_SCOPE)
endfunction()
function(req hay needle msg)
  string(FIND "${hay}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "Batch45 contract failed: ${msg}: missing [${needle}]")
  endif()
endfunction()
read_file("MainWindow.cpp" MW)
read_file("MainWindow.ui" UI)
read_file("ui/CaptureSessionWidget.cpp" CS)
read_file("ui/RemoteToolDialog.cpp" RT)
read_file("diagnostic/DeviceDiscoveryController.cpp" DD)
req("${UI}" "自定义抓包" "capture mode must expose custom capture")
req("${UI}" "抓包过滤条件" "BPF wording must be plain-language")
req("${MW}" "刷新接口" "capture workspace must provide interface refresh")
req("${MW}" "tun0" "interface discovery/help must cover VPN tunnel interfaces")
req("${DD}" "ifconfig 2>/dev/null" "interface inventory must come from actual ifconfig output")
req("${MW}" "串口通信" "serial terminal workspace must expose serial communication category")
req("${MW}" "串口与网络时间线" "serial/network combined timeline must exist")
req("${MW}" "新建抓包窗口" "multi-window capture entry must be visible")
req("${CS}" "QComboBox" "independent capture window interface selector must be editable combo")
req("${CS}" "setEditable(true)" "independent capture window interface selector must accept manual input")
req("${RT}" "只读检查" "tool/quick-command wording must be simplified into plain categories")
req("${RT}" "查看进程" "tool labels must be plain-language")
req("${RT}" "查看模组和信号" "module tool label must be plain-language")
message(STATUS "Batch45 capture interfaces/serial workspace contract passed")
