cmake_minimum_required(VERSION 3.16)
get_filename_component(ROOT "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
function(require_contains file needle message_text)
  file(READ "${ROOT}/${file}" content)
  string(FIND "${content}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "Batch42 contract: ${message_text} (${needle})")
  endif()
endfunction()
require_contains("diagnostic/ConnectivityProbe.h" "isUsableWanInterfaceName" "shared WAN-interface validation must exist")
require_contains("diagnostic/DeviceDiscoveryController.cpp" "ConnectivityProbe::isUsableWanInterfaceName" "discovery must reject LAN/bridge interface hints")
require_contains("MainWindow.cpp" "未识别到可用 WAN 接口，检测已停止" "UI must report WAN interface as unrecognized rather than substitute br0")
require_contains("MainWindow.cpp" "labelConnectionState" "responsive connection layout must explicitly manage connection status")
require_contains("README_BATCH42.txt" "br0" "Batch42 release note must document bridge rejection")
message(STATUS "Batch42 WAN-interface/layout regression contract passed")
