set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
function(require_contains path needle)
  file(READ "${ROOT}/${path}" TEXT)
  string(FIND "${TEXT}" "${needle}" POS)
  if(POS EQUAL -1)
    message(FATAL_ERROR "Batch38: ${path} missing: ${needle}")
  endif()
endfunction()

# Field deployments have three topology modes: primary only, backup only, or both.
# Default/placeholder bkup_* keys alone must not force dual-link classification.
require_contains("diagnostic/DiagnosticTypes.h" "wanTopology")
require_contains("diagnostic/LogAnalyzer.cpp" "primary-only")
require_contains("diagnostic/LogAnalyzer.cpp" "backup-only")
require_contains("diagnostic/LogAnalyzer.cpp" "dual")
require_contains("diagnostic/LogAnalyzer.cpp" "primaryPathPresent")
require_contains("diagnostic/LogAnalyzer.cpp" "backupPathPresent")
require_contains("diagnostic/DiagnosisEngine.cpp" "仅主链路")
require_contains("diagnostic/DiagnosisEngine.cpp" "仅备链路")
require_contains("diagnostic/DiagnosisEngine.cpp" "主备双链")
require_contains("tests/test_loganalyzer.cpp" "nvramShowClassifiesPrimaryOnlyTopology")
require_contains("tests/test_loganalyzer.cpp" "nvramShowClassifiesBackupOnlyTopology")
require_contains("tests/test_loganalyzer.cpp" "nvramShowClassifiesDualTopology")
require_contains("tests/CMakeLists.txt" "test_batch38_wan_topology_contract")
message(STATUS "Batch38 WAN topology contract passed")
