cmake_minimum_required(VERSION 3.16)
set(ROOT "${CMAKE_CURRENT_LIST_DIR}/..")
function(read_file rel out)
  file(READ "${ROOT}/${rel}" _content)
  set(${out} "${_content}" PARENT_SCOPE)
endfunction()
function(require_contains text needle label)
  string(FIND "${text}" "${needle}" pos)
  if(pos EQUAL -1)
    message(FATAL_ERROR "Batch30 missing ${label}: ${needle}")
  endif()
endfunction()

read_file("diagnostic/AtStatusParser.cpp" at)
require_contains("${at}" "parseRegistration" "structured registration parser")
require_contains("${at}" "registrationStatusText" "registration status text")
require_contains("${at}" "cmeErrorText" "CME decoding")
require_contains("${at}" "rejectCauseText" "registration reject-cause decoding")
require_contains("${at}" "parseOperator" "operator parser")

read_file("diagnostic/DeviceDiscoveryController.cpp" discovery)
foreach(cmd "AT+CGATT?" "AT+CSQ" "AT+COPS?")
  require_contains("${discovery}" "${cmd}" "AT telemetry ${cmd}")
endforeach()
require_contains("${discovery}" "QRegularExpression cme" "CME regex declaration")
require_contains("${discovery}" "CME ERROR" "CME regex content")

read_file("capture/PacketParser.cpp" parser)
require_contains("${parser}" "LinuxSll2" "SLL2 packet parsing")
require_contains("${parser}" "0x88a8" "QinQ parsing")

read_file("capture/TcpdumpTextStreamParser.cpp" live)
require_contains("${live}" "LinuxSll2" "live SLL2 parsing")
require_contains("${live}" "expectedLength" "live incremental packet finalize")
require_contains("${live}" "packetType<=4" "SLL2 packet-type sanity guard")

read_file("capture/TcpdumpTextPcapConverter.cpp" converter)
require_contains("${converter}" "LinuxSll2" "offline text SLL2 conversion")
require_contains("${converter}" "LinuxSll" "offline text SLL conversion")
require_contains("${converter}" "packetType<=4" "offline SLL2 packet-type sanity guard")

read_file("capture/PacketAnalyzer.cpp" analyzer)
require_contains("${analyzer}" "tcpPayloadLength>0" "payload-only retransmission")
require_contains("${analyzer}" "m_pendingSyn.remove(rev)" "RST/SYN response cleanup")

read_file("diagnostic/ChannelAnalyzer.cpp" channel)
require_contains("${channel}" "betterMainSession" "lexicographic main session selection")
require_contains("${channel}" "主业务会话" "main session report label")
require_contains("${channel}" "历史连接异常" "historical session separation")

read_file("diagnostic/LogAnalyzer.cpp" log)
require_contains("${log}" "physicalLinkDownCount" "historical link event counter")
require_contains("${log}" "link up" "link recovery")
require_contains("${log}" "parseOperator" "COPS log parsing")

read_file("telnet/TelnetClient.cpp" telnet)
require_contains("${telnet}" "__FF_CMD_DONE_" "unique command marker")
require_contains("${telnet}" "sanitizeCommandOutput" "command echo sanitization")
require_contains("${telnet}" "lastCommandExitCode" "exit code capture")
require_contains("${telnet}" "MaxCommandTextBuffer" "bounded long-command text buffer")

read_file("diagnostic/DualCaptureCorrelator.cpp" dual)
require_contains("${dual}" "payloadHash" "NAT-safe payload correlation")
require_contains("${dual}" "时间差" "cross-side delay evidence")

read_file("MainWindow.cpp" main)
require_contains("${main}" "failSynchronizedWorkflowCapture" "synchronized capture sibling cleanup")
require_contains("${main}" "m_dualCaptureCorrelator" "dual capture correlation integration")
require_contains("${main}" "Iec104SessionAnalyzer::analyze" "IEC104 session integration")
require_contains("${main}" "20000" "bounded realtime UI rows")

read_file("protocol/ProtocolDiagnosis.cpp" proto)
require_contains("${proto}" "IEC104 I帧发送序号跳变" "IEC104 sequence diagnosis")
require_contains("${proto}" "STOPDT act" "IEC104 stop state")
require_contains("${proto}" "TESTFR act" "IEC104 test state")

read_file("capture/PacketCaptureController.cpp" capture)
require_contains("${capture}" "QDir::tempPath" "system temporary PCAP storage")
require_contains("${capture}" "m_tempCapture.write" "stream-to-disk capture")

read_file("report/ReportExporter.cpp" report)
require_contains("${report}" "operatorName" "operator report")
require_contains("${report}" "physicalLinkDownCount" "historical WAN event report")

message(STATUS "Batch30 parser/diagnostics hardening contract passed")
